plugins:
  - 'prettier-plugin-astro'
trailingComma: "all"
tabWidth: 2
semi: false
singleQuote: true
jsxSingleQuote: true
quoteProps: consistent
cursorOffset: -1
bracketSameLine: true
overrides: [
    {
      files: '*.astro',
      options: {
        parser: 'astro',
      },
    },
  ]
